### ISSUE TITLE
Bigmemory gives an error in R CMD CHECK environment

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/bigmemory#19]
From @cdeterman. The primary problem appears to be in the big.matrix.Rd file with the example

x <- big.matrix(10, 2, type='integer', init = -5)

Strangely this returns the error

Error: memory could not be allocated for instance of type big.matrix
where somehow CreateSharedMatrix is returning a null address. This is very odd as it works without a problem when run in the R console even when multiple big.matrix objects are created consecutively. The only way I have been able to reproduce the error is by rerunning R CMD CHECK or R --vanilla < bigmemory-Ex.R where bigmemory-Ex.R was previously produced by R CMD CHECK.

**Comment by kaneplusplus** [comment]
Please note: I've removed a \dontrun from the attach.big.matrix documentation. This is make it easier for Kurt Hornik to take a look at the problem.

**Comment by cdeterman** [comment]
I see there was a merge stating that the \dontrun bug was fixed.  What was the problem?

**Comment by kaneplusplus** [comment]
I've got it fixed on *nix. For shared-memory matrices the check environment was trying to use the same shared name more than once, which was causing a problem. My guess is that the random seed is set to a constant and, as a result, the same resource name was generated more than once.

I'm verifying it works on Windows. AppVeyor feels slow when debugging.

However, I'm not really sure. The problem started with my April 19th checkin. I'm not sure how it could have triggered the problem.

**Comment by privefl** [comment]
Still get this problem when checking a package that creates a big.matrix object in examples.
The error seems to disappear when using `shared = FALSE`.
And, the error seems to not happen when using `as.big.matrix` from a `matrix` object.

PS: tested on Windows

**Comment by kaneplusplus** [comment]
I'll take another look. I'm pretty bandwidth-limited this week though.

**Comment by privefl** [comment]
I think we get this error when we don't have enough shared memory space available. Especially, when I'm crashing my R sessions lots of time.
I use http://stackoverflow.com/a/4262545/6103040 to get some space back. It usually works.

**Comment by cdeterman** [comment]
@kaneplusplus was this actually solved?  I thought @privefl just made an observation?  It shouldn't be a requirement for a user to need to manually clean up processes from the commandline.

**Comment by privefl** [comment]
I think we cannot do much about it, unfortunately.
